### ISSUE TITLE
ModuleNotFoundError: No module named 'opensr_test'

### ISSUE THREAD

**Issue by robmarkcole** [ESAOpenSR/opensr-test#1]
Having run `pip install opensr-test` in a fresh venv and validated with `pip freeze`, I get the dreaded `ModuleNotFoundError`.

I then `pip install git+https://github.com/ESAOpenSR/opensr-test` and get `ModuleNotFoundError: No module named 'cv2'`

I then `pip install opencv-python` and can then successfully `import opensr_test`

**Comment by csaybar** [comment]
Hi Robin, we have just released the package version associated with the paper. You should be able to install it easily by running 'pip install opensr-test'.  🤗
